Added main benefit receiving variables and renamed jobseeker_support_…
digitalaotearoa/openfisca-aotearoa pull request #37
Opened 2022-11-01 02:18 UTC by verbman

* Tax and benefit system evolution. Minor change.
* Impacted periods: all.
* Impacted areas: `openfisca_aotearoa/variables/acts/social_security/`
* Details:
* Added variables:
  - `social_security__recieving_main_benefit`
  - `emergency_benefit__receiving`
  - `sole_parent_support__receiving`
  - `supported_living_payment__receiving`
  - `young_parent_payment__receiving`
  - `youth_payment__receiving`
* Renamed variables:
  - `jobseeker_benefit__granted` to `jobseeker_support__granted`
- - - -

These changes:

- Impact the OpenFisca-Aotearoa public API (for instance renaming or removing a variable)
- Add a new feature (for instance adding a variable)

2022-11-02 14:00 UTC, maukoquiroga submitted a review, later dismissed
Depends on #33 ;)

2022-11-08 04:10 UTC, Br3nda commented on CHANGELOG.md
> +  - `emergency_benefit__receiving`
I before E, but not after C

```suggestion
  - `social_security__receiving_main_benefit`
  - `emergency_benefit__receiving`
```

2022-11-08 04:10 UTC, Br3nda commented on openfisca_aotearoa/tests/social_security/jobseeker_support/jobseeker_support__base.yaml
> +    social_security__recieving_main_benefit:
```suggestion
    social_security__receiving_main_benefit:
```

2022-11-08 04:10 UTC, Br3nda commented on openfisca_aotearoa/tests/social_security/main_benefits.yaml
> +    social_security__recieving_main_benefit:
```suggestion
    social_security__receiving_main_benefit:
```

2022-11-08 04:11 UTC, Br3nda approved these changes
looks good, but the spelling is wrong

2022-11-08 04:11 UTC, Br3nda requested changes, later dismissed
fix spelling

2022-11-21 21:40 UTC, MarkCalvert approved these changes

2022-11-21 21:45 UTC, merged