Child disability allowance
digitalaotearoa/openfisca-aotearoa pull request #41
Opened 2022-11-21 22:28 UTC by asgharkazi

* Tax and benefit system evolution. | Technical improvement. | Crash fix. | Minor change.
* Impacted periods: all. | until DD/MM/YYYY. | from DD/MM/YYYY.
* Impacted areas: `path/to/file/containing/impacted/variables`
* Details:
  - New feature or new behaviour description
  - Cases for which an error was noticed

- - - -

These changes:
- Impact the OpenFisca-Aotearoa public API (for instance renaming or removing a variable)
- Add a new feature (for instance adding a variable)
- Fix or improve an already existing calculation.

2022-11-27 23:33 UTC, maukoquiroga requested changes
Looks good. As it depends on the other one, please re-send me a review request once the other one qgets merged.

2022-11-27 23:33 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/social_security/disability_allowance/disability_allowance.py
> +class disability_allowance__current_income(variables.Variable):
What is the difference with pure _income_?

2022-11-27 23:33 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/social_security/disability_allowance/disability_allowance.py
> +class disability_allowance__family_income(variables.Variable): # Copied from social security job_seeker formulas
Could the scope of this definition be broader? Prefixing should be the exception, is family income defined differently for disability allowance than for jobseeker support, or other benefits, or could it be generalised?

2022-11-27 23:33 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/social_security/disability_allowance/disability_allowance.py
> +        no_partners = (persons("person_has_partner", period) == 0)
Couldn't we rationalise here the use of _person_has_parner_ and _in_a_relartionship_?

2022-11-27 23:33 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/social_security/disability_allowance/disability_allowance.py
> +        persons("disability_allowance__sole_parent_meets_relationship_qualification", period)
Same as in the other PR, you have to sum here.

2022-11-27 23:33 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/social_security/disability_allowance/disability_allowance.py
> +        only_one_child = (persons("social_security__dependent_children", period) == 1)
You hacve to sum here.

2022-11-27 23:33 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/social_security/disability_allowance/disability_allowance.py
> +        in_relationship = persons("person_has_partner", period) #refactor this to person_has_partner
If you rebase from main you'll see that I rationalised the usde of this varfiabvle

2022-11-28 22:34 UTC, MarkCalvert approved these changes
Will add requested changes in a future PR

2024-03-07 21:17 UTC, closed without merging