Feature/sole parent support
digitalaotearoa/openfisca-aotearoa pull request #43
Opened 2022-11-23 23:43 UTC by verbman

Thanks for contributing to OpenFisca !

* Tax and benefit system evolution.
* Impacted periods: Social Security
* Impacted areas: `openfisca-aotearoa/variables/social_security`
* Details:
  - Sole Parent Support benefit

- - - -

These changes _(remove lines which are not relevant to your contribution)_:

- Impact the OpenFisca-Aotearoa public API
- Add a new feature
- Fix or improve an already existing calculation.
- Change non-functional parts of this repository (for instance editing the README)

2022-11-27 23:49 UTC, maukoquiroga requested changes, later dismissed
Great work! Couple of quetions though.

2022-11-27 23:49 UTC, maukoquiroga commented on CHANGELOG.md
> +# 17.2.0 - [42](https://github.com/govzeroaotearoa/openfisca-aotearoa/pull/42)
Do not forget to bump also the `setup.py` file.

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/entities.py
> +        {
This is exclusive with principal, right?

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/tests/social_security/sole_parent_support/sole_parent_support__split_care.yaml
> +- name: Sole Parent Split Care, no one eligible - why is this false and not incalculatable?
Default valure?

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/tests/social_security/sole_parent_support/sole_parent_support__split_care.yaml
> +        principal: Koro
I don't get this. The benefit is calculated for P or for the family?

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/citizenship/citizenship.py
> +from openfisca_core.periods import DateUnit, DAY, ETERNITY
```suggestion
from openfisca_core.periods import DateUnit
```

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/citizenship/citizenship.py
> +from openfisca_aotearoa.variables.demographics.residence import days_since_n_years_ago
```suggestion
from openfisca_aotearoa.variables.demographics import residence
```

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/oranga_tamariki/interpretation/child.py
> +from openfisca_core import periods, variables
```suggestion
from openfisca_core import holders, periods, variables
```

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/oranga_tamariki/interpretation/child.py
>  from openfisca_core import holders
```suggestion
```

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/tests/social_security/sole_parent_support/sole_parent_support__split_care.yaml
> +        principal: Koro
Here as you're using _social_security__principal_caregiver_ you could instead declare Koro as parent, no?

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/social_security/sole_parent_support/sole_parent_support.py
> +        dc = persons.family.members("social_security__dependent_child", period.first_week) * \
What's the corresponding clausde ?

2022-11-27 23:49 UTC, maukoquiroga commented on openfisca_aotearoa/variables/acts/social_security/sole_parent_support/sole_parent_support.py
> +        return persons.family.any(dc, role=entities.Family.CHILD) * (persons.has_role(entities.Family.PRINCIPAL) + persons.has_role(entities.Family.PARENT))
Interesting.

I would have thought you were going to use _social_security__principal_caregiver_ for this:

```suggestion
        principal = people("social_security__principal_caregiver", period)
        children = persons.family.any(dc, role=entities.Family.CHILD)
        parent = persons.has_role(entities.Family.PARENT)
        return principal * children * parent
```

2022-11-28 22:35 UTC, MarkCalvert approved these changes
Will add requested changes in a future PR

2022-11-29 21:51 UTC, merged